-- local view = require "nvim-tree.view"
-- local tree = {}
-- offsets = {{filetype = "NvimTree", text = "File Explorer", highlight = "Directory", text_align = "left"}}
-- tree.open = function()
--   -- require "bufferline.state".set_offset(51, "FileTree")
--   require "nvim-tree".find_file(true)
-- end
-- tree.close = function()
--   -- require "bufferline.state".set_offset(0)
--   require "nvim-tree".close()
-- end
-- tree.toggle_tree = function()
--   if view.win_open() then
--     -- require "bufferline.state".set_offset(0)
--     require "nvim-tree".close()
--   else
--     -- require "bufferline.state".set_offset(51, "File Explorer")
--     require "nvim-tree".find_file(true)
--   end
-- end
-- return tree
