-- vim.filetype.add({
--     extension = {
--         foo = "fooscript",
--     },
--     filename = {
--         ["Foofile"] = "fooscript",
--     },
--     pattern = {
--         ["~/%.config/foo/.*"] = "fooscript",
--     }
-- })
